object FindTranslations:

  /** Generate `translations-GENERATED.scala` from the authoritative Swedish -> English concept
    * translations in glossary/concepts.scala (glossary.explain.allConcepts) — the same source
    * the glossary tables use.
    *
    * ⚠ THIS WRITES ONLY INTO `target/` (2026-08-22). It used to ALSO write straight into a sibling
    * muntabot clone, guarded by nothing but `os.exists(dest)`, so a plain `sbt gen` silently
    * dirtied a repository the user never asked to touch, on any box that had muntabot cloned. That
    * turns a COMPILE into a cross-repo write, which is the inverse of the rule that reaching another
    * repo is a deliberate act. `FindHeadings` was fixed this way on 2026-08-21; this was the last
    * writer still doing it, and it survived only because its content happened to be identical each
    * time, so nothing ever showed up dirty to give it away.
    *
    * Distribution is the explicit opt-in step: `sbt syncMuntabot`. Keep generation and distribution
    * separate. */
  def apply(): Unit = util.Try {
    val source = "translations-GENERATED.scala"
    val out = os.pwd / "target" / source

    def esc(x: String): String = x.replace("\\", "\\\\").replace("\"", "\\\"")

    val pairs = glossary.explain.allConcepts
      .filter(_.en.nonEmpty)
      .map(c => (c.sv, c.en))
      .distinctBy(_._1)
      .sortBy(_._1.toLowerCase)
    println(s"Collected ${pairs.size} authoritative sv->en translations from glossary")

    val entries = pairs.map((sv, en) => s""""${esc(sv)}" -> "${esc(en)}"""")

    val generatedCode =
      s"""|package shared
          |
          |  /** Generated by introprog plan/FindTranslations.scala:
          |    * authoritative Swedish -> English concept translations,
          |    * sourced from glossary/concepts.scala (explain.allConcepts). */
          |  lazy val translateSvEn: Map[String, String] = Map(
          |${entries.mkString("    ", ",\n    ", ",\n    ")}
          |  )
          |""".stripMargin

    println(s"Saving: $out")
    os.write.over(out, generatedCode)
  } match
    case util.Failure(exception) =>
      println(Console.RED + s"Failed to generate translations: $exception" + Console.RESET)
    case util.Success(_) =>
      println(Console.GREEN + "OK! Successful translations generation done!" + Console.RESET)
