object FindTranslations:

  /** Generate muntabot's translations-GENERATED.scala from the authoritative
    * Swedish -> English concept translations in glossary/concepts.scala
    * (glossary.explain.allConcepts) — the same source the glossary tables use. */
  def apply(): Unit = util.Try {
    val source = "translations-GENERATED.scala"
    val out = os.pwd / "target" / source
    val dest =
      os.pwd / os.up / os.up / "bjornregnell" / "muntabot" / "src" / "main" / "scala"

    def esc(x: String): String = x.replace("\\", "\\\\").replace("\"", "\\\"")

    val pairs = glossary.explain.allConcepts
      .filter(_.en.nonEmpty)
      .map(c => (c.sv, c.en))
      .distinctBy(_._1)
      .sortBy(_._1.toLowerCase)
    println(s"Collected ${pairs.size} authoritative sv->en translations from glossary")

    val entries = pairs.map((sv, en) => s""""${esc(sv)}" -> "${esc(en)}"""")

    val generatedCode =
      s"""|package shared
          |
          |  /** Generated by introprog plan/FindTranslations.scala:
          |    * authoritative Swedish -> English concept translations,
          |    * sourced from glossary/concepts.scala (explain.allConcepts). */
          |  lazy val translateSvEn: Map[String, String] = Map(
          |${entries.mkString("    ", ",\n    ", ",\n    ")}
          |  )
          |""".stripMargin

    println(s"Saving: $out")
    os.write.over(out, generatedCode)
    if os.exists(dest) then
      println(s"Saving: $dest/$source")
      os.write.over(dest / source, generatedCode)
    else
      println(
        Console.YELLOW + s"Cannot copy file to missing dir $dest \n  clone bjornregnell/muntabot" + Console.RESET
      )
  } match
    case util.Failure(exception) =>
      println(Console.RED + s"Failed to generate translations: $exception" + Console.RESET)
    case util.Success(_) =>
      println(Console.GREEN + "OK! Successful translations generation done!" + Console.RESET)
      println(Console.YELLOW + "TODO: Rebuild with muntabot/publish.sh" + Console.RESET)
